import 'package:flutter/material.dart';
import 'package:flutterapp/mobile_spgapp/generatedartikelwidget2/generated/GeneratedArtikellainnyaWidget.dart';
import 'package:flutterapp/mobile_spgapp/generatedartikelwidget2/generated/GeneratedArtikelWidget3.dart';
import 'package:flutterapp/mobile_spgapp/generatedartikelwidget2/generated/GeneratedBerkasberkasyangharusdisiapkanuntukDaftarUlangsecaraOff.dart';
import 'package:flutterapp/mobile_spgapp/generatedartikelwidget2/generated/GeneratedBannerWidget1.dart';
import 'package:flutterapp/mobile_spgapp/generatedartikelwidget2/generated/GeneratedHeaderWidget1.dart';

/* Frame Artikel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArtikelWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 91.80327606201172,
                child: GeneratedBannerWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 139.0,
                child: GeneratedArtikelWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 460.0,
                height: 175.4481201171875,
                child: GeneratedArtikellainnyaWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 142.0,
                child:
                    GeneratedBerkasberkasyangharusdisiapkanuntukDaftarUlangsecaraOff(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 80.0,
                child: GeneratedHeaderWidget1(),
              )
            ]),
      ),
    ));
  }
}
