import 'package:flutter/material.dart';
import 'package:flutterapp/mobile_spgapp/generateddatapendaftaranwidget/generated/GeneratedButtonKembaliWidget.dart';
import 'package:flutterapp/mobile_spgapp/generateddatapendaftaranwidget/generated/GeneratedFormWidget11.dart';
import 'package:flutterapp/mobile_spgapp/generateddatapendaftaranwidget/generated/GeneratedJudulWidget5.dart';
import 'package:flutterapp/mobile_spgapp/generateddatapendaftaranwidget/generated/GeneratedHeaderWidget7.dart';

/* Frame Data Pendaftaran
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDataPendaftaranWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 900.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 900.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 310.0,
                              height: 506.6666564941406,
                              child: GeneratedFormWidget11(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 236.0,
                              height: 28.0,
                              child: GeneratedJudulWidget5(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 700.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 20.0,
                              child: GeneratedButtonKembaliWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 80.0,
                              child: GeneratedHeaderWidget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
