import 'package:flutter/material.dart';
import 'package:flutterapp/mobile_spgapp/generatedpendaftaran1widget/generated/GeneratedHeaderWidget6.dart';
import 'package:flutterapp/mobile_spgapp/generatedpendaftaran1widget/generated/GeneratedPendaftaranWidget1.dart';
import 'package:flutterapp/mobile_spgapp/generatedpendaftaran1widget/generated/GeneratedFormWidget7.dart';

/* Frame Pendaftaran - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPendaftaran1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 33.0,
                              child: GeneratedPendaftaranWidget1(),
                            ),
                            Positioned(
                              left: 35.73779296875,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 288.52459716796875,
                              height: 783.0,
                              child: GeneratedFormWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 80.0,
                              child: GeneratedHeaderWidget6(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
