import 'package:flutter/material.dart';
import 'package:flutterapp/mobile_spgapp/generatedopenmenuwidget/generated/GeneratedBasemenuWidget.dart';
import 'package:flutterapp/mobile_spgapp/generatedopenmenuwidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/mobile_spgapp/generatedopenmenuwidget/generated/GeneratedHeadermenuWidget.dart';

/* Frame Open Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOpenMenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 250.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 800.0,
                child: GeneratedBasemenuWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 169.2624969482422,
                height: 80.0,
                child: GeneratedHeadermenuWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 88.0,
                child: GeneratedButtonWidget(),
              )
            ]),
      ),
    ));
  }
}
