import 'package:flutter/material.dart';

/* UndefinedNode NIS 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNIS2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
