import 'package:flutter/material.dart';
import 'package:flutterapp/mobile_spgapp/generatedperingatanpendaftaranwidget/generated/GeneratedRectangle96Widget.dart';
import 'package:flutterapp/mobile_spgapp/generatedperingatanpendaftaranwidget/generated/GeneratedSelamataAndatelahmenyelesaikanpendaftaranWidget.dart';
import 'package:flutterapp/mobile_spgapp/generatedperingatanpendaftaranwidget/generated/GeneratedButton2Widget3.dart';
import 'package:flutterapp/mobile_spgapp/generatedperingatanpendaftaranwidget/generated/GeneratedRectangle95Widget1.dart';

/* Frame Peringatan - Pendaftaran
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPeringatanPendaftaranWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 300.0,
      height: 220.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 300.0,
              height: 220.0,
              child: GeneratedRectangle95Widget1(),
            ),
            Positioned(
              left: 70.0,
              top: 148.0,
              right: null,
              bottom: null,
              width: 160.0,
              height: 30.0,
              child: GeneratedButton2Widget3(),
            ),
            Positioned(
              left: 125.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 50.0,
              child: GeneratedRectangle96Widget(),
            ),
            Positioned(
              left: 47.0,
              top: 40.0,
              right: null,
              bottom: null,
              width: 208.0,
              height: 40.0,
              child: GeneratedSelamataAndatelahmenyelesaikanpendaftaranWidget(),
            )
          ]),
    ));
  }
}
