import 'package:flutter/material.dart';
import 'package:flutterapp/mobile_spgapp/generatedhomepagewidget/generated/GeneratedBannerWidget.dart';
import 'package:flutterapp/mobile_spgapp/generatedhomepagewidget/generated/GeneratedArtikelWidget.dart';
import 'package:flutterapp/mobile_spgapp/generatedhomepagewidget/generated/GeneratedHeaderWidget.dart';

/* Frame Home page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 76.66666412353516,
                child: GeneratedBannerWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 482.0724792480469,
                child: GeneratedArtikelWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 80.0,
                child: GeneratedHeaderWidget(),
              )
            ]),
      ),
    ));
  }
}
