import 'package:flutter/material.dart';

/* UndefinedNode Nilai 80
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNilai80Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
