import 'package:flutter/material.dart';

/* UndefinedNode Nilai 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNilai85Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
