import 'package:flutter/material.dart';

/* UndefinedNode Nilai 95
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNilai95Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
