import 'package:flutter/material.dart';

/* UndefinedNode Check
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
