import 'package:flutter/material.dart';

/* UndefinedNode Component 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponent1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(),
    ));
  }
}
